export type OpenChamberSection =
  | 'visual'
  | 'chat'
  | 'shortcuts'
  | 'sessions'
  | 'modelMode'
  | 'git'
  | 'github'
  | 'notifications'
  | 'voice'
  | 'tunnel'
  | 'cron'
  | 'heartbeat'
  | 'telegram'
  | 'superwords';
